export const actionTypes = {
  UPDATE_TODO: "UPDATE_TODO",
  CHANGE_GUEST_TO_MEMBER: "CHANGE_GUEST_TO_MEMBER",
  STAY_TO_MEMBER: "STAY_TO_MEMBER",
  CHANGE_INPUT_HEADER: "CHANGE_INPUT_HEADER",
  CHANGE_INPUT_DES: "CHANGE_INPUT_DES",
  ADD_NEW_TODO: "ADD_NEW_TODO",
  GO_TO_DONE: "GO_TO_DONE",
  GO_BACK_DOING: "GO_BACK_DOING",
  GET_TODO_LIST_FROM_DATABASE: "GET_TODO_LIST_FROM_DATABASE",
};
